config/routes.rb
Rails.application.routes.draw do

  get 'collector/index'
  get 'collector/show'

  resources :accounts
  resources :incidents

end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/incident.rb
class Incident < ActiveRecord::Base
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	def index
		@accounts = Account.all
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/collector_controller.rb
class CollectorController < ApplicationController
	def index
		@time = Time.now
	end

	def show
		@time = Time.now
	end

end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collector_helper.rb
module CollectorHelper
end

app/views/accounts/index.html.haml
%h2 This is the index for accounts

- @accounts.each do |account|
  %p= account.sales_priority
  %p= account.name
  %p= account.owner
  %p= account.collector
  %p= account.shard
  %p= account.expiration

app/views/collector/index.html.haml
%h1 This is the headline 1
%h2 This is the headline 2
%h3 This is the headline 3

%p= @time

%p test



= link_to 'Get to the show page', collector_show_path

%a { href: "#", title: "test"}

/ %a href="#" onclick="this.style.backgroundColor='#009900';this.style.color='#FFFFFF';" Paint it green

app/views/collector/show.html.erb
<p>Test</p>
<p><%= @time %></p>

<%= link_to 'path to index...', collector_index_path %>

<a href="#" onclick="this.style.backgroundColor='#99000">Red</a>

app/views/incidents/index.html.haml
%h2
  This is the index for incidents!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HamlJquery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>